apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: 'YXNkZg==' # base64 encoded admin
  MONGO_INITDB_ROOT_PASSWORD: 'MTIzNA==' # base64 encoded pass123
