apiVersion: v1
kind: Secret
metadata:
  name: grade-submission-api-secret
  namespace: grade-submission
type: Opaque
data:
  MONGODB_USER: 'YXNkZg==' # base64 encoded admin
  MONGODB_PASSWORD: 'MTIzNA==' # base64 encoded pass123
